language: php

php:
  - 5.3  

script:
  - phpunit
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs CodeSniffer.php CodeSniffer --standard=PEAR --report=summary --ignore=*/tests/* -np
 